### PR TITLE
User can choose a date they like to travel.

### PR DESCRIPTION
**Pull request by vincelavang**
screen shot 2017-06-19 at 2 04 54 pm

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
- [ ] Use bootstrap form css.
- [ ] Ensure nice vertical spacing.
- [ ] Consider using a definition list (or probably a table instead) element for your place details.
- [ ] Consider using a bootstrap thumbnail component for rendered place details
- [ ] Add some whitespace to the top of your page.

**Comment by ronperris** [comment]
👍 🚢

**Review by ronperris — APPROVED** [review]
Looks good.

**Comment by vincelavang** [comment]
screen shot 2017-06-21 at 10 10 24 am

**Comment by vincelavang** [comment]
screen shot 2017-06-21 at 10 10 36 am

**Pull request merged**
